### PR TITLE
Create Both of you - Steven Universe Cover.alda

### PR DESCRIPTION
**Pull request by elydpg**

### CODE REVIEW

**Comment by elydpg** [comment]
Am I going to have to do this for every score I want to upload?

**Comment by bring2dip** [comment]
If there are many scores you can send pr in 1 single commit

**Comment by elydpg** [comment]
It seems as though every single file creation triggers a new PR...

**Comment by bring2dip** [comment]
First you can commit your changes in a single branch and sync to github in your repo. Then you can create PR from there. This way it would be only one PR. For now, I have merged it all. I will update the page as well

**Pull request merged**
